/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sync_pb.GetUpdatesCallerInfo', null, global);
goog.exportSymbol('proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.GetUpdatesCallerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.GetUpdatesCallerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.GetUpdatesCallerInfo.displayName = 'proto.sync_pb.GetUpdatesCallerInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.GetUpdatesCallerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.GetUpdatesCallerInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.GetUpdatesCallerInfo.toObject = function(includeInstance, msg) {
  var obj = {
    source: jspb.Message.getField(msg, 1),
    notificationsEnabled: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.GetUpdatesCallerInfo}
 */
proto.sync_pb.GetUpdatesCallerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.GetUpdatesCallerInfo;
  return proto.sync_pb.GetUpdatesCallerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.GetUpdatesCallerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.GetUpdatesCallerInfo}
 */
proto.sync_pb.GetUpdatesCallerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource} */ (reader.readEnum());
      msg.setSource(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationsEnabled(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.GetUpdatesCallerInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.GetUpdatesCallerInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.GetUpdatesCallerInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource = {
  UNKNOWN: 0,
  FIRST_UPDATE: 1,
  LOCAL: 2,
  NOTIFICATION: 3,
  PERIODIC: 4,
  SYNC_CYCLE_CONTINUATION: 5,
  NEWLY_SUPPORTED_DATATYPE: 7,
  MIGRATION: 8,
  NEW_CLIENT: 9,
  RECONFIGURATION: 10,
  DATATYPE_REFRESH: 11,
  RETRY: 13,
  PROGRAMMATIC: 14
};

/**
 * required GetUpdatesSource source = 1;
 * @return {!proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.getSource = function() {
  return /** @type {!proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.sync_pb.GetUpdatesCallerInfo.GetUpdatesSource} value */
proto.sync_pb.GetUpdatesCallerInfo.prototype.setSource = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.clearSource = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.hasSource = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool notifications_enabled = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.getNotificationsEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.sync_pb.GetUpdatesCallerInfo.prototype.setNotificationsEnabled = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.clearNotificationsEnabled = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.GetUpdatesCallerInfo.prototype.hasNotificationsEnabled = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.sync_pb);
