/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sync_pb = require('./sync_pb.js');
goog.object.extend(proto, sync_pb);
goog.exportSymbol('proto.sync_pb.ModelTypeState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.ModelTypeState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.ModelTypeState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.ModelTypeState.displayName = 'proto.sync_pb.ModelTypeState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.ModelTypeState.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.ModelTypeState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.ModelTypeState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.ModelTypeState.toObject = function(includeInstance, msg) {
  var obj = {
    progressMarker: (f = msg.getProgressMarker()) && sync_pb.DataTypeProgressMarker.toObject(includeInstance, f),
    typeContext: (f = msg.getTypeContext()) && sync_pb.DataTypeContext.toObject(includeInstance, f),
    encryptionKeyName: jspb.Message.getField(msg, 3),
    initialSyncDone: jspb.Message.getField(msg, 4),
    cacheGuid: jspb.Message.getField(msg, 5),
    authenticatedAccountId: jspb.Message.getField(msg, 6)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.ModelTypeState}
 */
proto.sync_pb.ModelTypeState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.ModelTypeState;
  return proto.sync_pb.ModelTypeState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.ModelTypeState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.ModelTypeState}
 */
proto.sync_pb.ModelTypeState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new sync_pb.DataTypeProgressMarker;
      reader.readMessage(value,sync_pb.DataTypeProgressMarker.deserializeBinaryFromReader);
      msg.setProgressMarker(value);
      break;
    case 2:
      var value = new sync_pb.DataTypeContext;
      reader.readMessage(value,sync_pb.DataTypeContext.deserializeBinaryFromReader);
      msg.setTypeContext(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEncryptionKeyName(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInitialSyncDone(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCacheGuid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthenticatedAccountId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.ModelTypeState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.ModelTypeState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.ModelTypeState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.ModelTypeState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProgressMarker();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      sync_pb.DataTypeProgressMarker.serializeBinaryToWriter
    );
  }
  f = message.getTypeContext();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      sync_pb.DataTypeContext.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional DataTypeProgressMarker progress_marker = 1;
 * @return {?proto.sync_pb.DataTypeProgressMarker}
 */
proto.sync_pb.ModelTypeState.prototype.getProgressMarker = function() {
  return /** @type{?proto.sync_pb.DataTypeProgressMarker} */ (
    jspb.Message.getWrapperField(this, sync_pb.DataTypeProgressMarker, 1));
};


/** @param {?proto.sync_pb.DataTypeProgressMarker|undefined} value */
proto.sync_pb.ModelTypeState.prototype.setProgressMarker = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearProgressMarker = function() {
  this.setProgressMarker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasProgressMarker = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DataTypeContext type_context = 2;
 * @return {?proto.sync_pb.DataTypeContext}
 */
proto.sync_pb.ModelTypeState.prototype.getTypeContext = function() {
  return /** @type{?proto.sync_pb.DataTypeContext} */ (
    jspb.Message.getWrapperField(this, sync_pb.DataTypeContext, 2));
};


/** @param {?proto.sync_pb.DataTypeContext|undefined} value */
proto.sync_pb.ModelTypeState.prototype.setTypeContext = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearTypeContext = function() {
  this.setTypeContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasTypeContext = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string encryption_key_name = 3;
 * @return {string}
 */
proto.sync_pb.ModelTypeState.prototype.getEncryptionKeyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.sync_pb.ModelTypeState.prototype.setEncryptionKeyName = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearEncryptionKeyName = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasEncryptionKeyName = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool initial_sync_done = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.getInitialSyncDone = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.sync_pb.ModelTypeState.prototype.setInitialSyncDone = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearInitialSyncDone = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasInitialSyncDone = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string cache_guid = 5;
 * @return {string}
 */
proto.sync_pb.ModelTypeState.prototype.getCacheGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.sync_pb.ModelTypeState.prototype.setCacheGuid = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearCacheGuid = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasCacheGuid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string authenticated_account_id = 6;
 * @return {string}
 */
proto.sync_pb.ModelTypeState.prototype.getAuthenticatedAccountId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.sync_pb.ModelTypeState.prototype.setAuthenticatedAccountId = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ModelTypeState.prototype.clearAuthenticatedAccountId = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ModelTypeState.prototype.hasAuthenticatedAccountId = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.sync_pb);
