/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var sync_enums_pb = require('./sync_enums_pb.js');
goog.object.extend(proto, sync_enums_pb);
goog.exportSymbol('proto.sync_pb.NavigationRedirect', null, global);
goog.exportSymbol('proto.sync_pb.ReplacedNavigation', null, global);
goog.exportSymbol('proto.sync_pb.SessionHeader', null, global);
goog.exportSymbol('proto.sync_pb.SessionSpecifics', null, global);
goog.exportSymbol('proto.sync_pb.SessionTab', null, global);
goog.exportSymbol('proto.sync_pb.SessionTab.FaviconType', null, global);
goog.exportSymbol('proto.sync_pb.SessionWindow', null, global);
goog.exportSymbol('proto.sync_pb.SessionWindow.BrowserType', null, global);
goog.exportSymbol('proto.sync_pb.TabNavigation', null, global);
goog.exportSymbol('proto.sync_pb.TabNavigation.BlockedState', null, global);
goog.exportSymbol('proto.sync_pb.TabNavigation.PasswordState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.SessionSpecifics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.SessionSpecifics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.SessionSpecifics.displayName = 'proto.sync_pb.SessionSpecifics';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.SessionHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sync_pb.SessionHeader.repeatedFields_, null);
};
goog.inherits(proto.sync_pb.SessionHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.SessionHeader.displayName = 'proto.sync_pb.SessionHeader';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.SessionWindow = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sync_pb.SessionWindow.repeatedFields_, null);
};
goog.inherits(proto.sync_pb.SessionWindow, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.SessionWindow.displayName = 'proto.sync_pb.SessionWindow';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.SessionTab = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sync_pb.SessionTab.repeatedFields_, null);
};
goog.inherits(proto.sync_pb.SessionTab, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.SessionTab.displayName = 'proto.sync_pb.SessionTab';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.TabNavigation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sync_pb.TabNavigation.repeatedFields_, null);
};
goog.inherits(proto.sync_pb.TabNavigation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.TabNavigation.displayName = 'proto.sync_pb.TabNavigation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.NavigationRedirect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.NavigationRedirect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.NavigationRedirect.displayName = 'proto.sync_pb.NavigationRedirect';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.ReplacedNavigation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.ReplacedNavigation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.ReplacedNavigation.displayName = 'proto.sync_pb.ReplacedNavigation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.SessionSpecifics.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.SessionSpecifics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.SessionSpecifics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionSpecifics.toObject = function(includeInstance, msg) {
  var obj = {
    sessionTag: jspb.Message.getField(msg, 1),
    header: (f = msg.getHeader()) && proto.sync_pb.SessionHeader.toObject(includeInstance, f),
    tab: (f = msg.getTab()) && proto.sync_pb.SessionTab.toObject(includeInstance, f),
    tabNodeId: jspb.Message.getFieldWithDefault(msg, 4, -1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.SessionSpecifics}
 */
proto.sync_pb.SessionSpecifics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.SessionSpecifics;
  return proto.sync_pb.SessionSpecifics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.SessionSpecifics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.SessionSpecifics}
 */
proto.sync_pb.SessionSpecifics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionTag(value);
      break;
    case 2:
      var value = new proto.sync_pb.SessionHeader;
      reader.readMessage(value,proto.sync_pb.SessionHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 3:
      var value = new proto.sync_pb.SessionTab;
      reader.readMessage(value,proto.sync_pb.SessionTab.deserializeBinaryFromReader);
      msg.setTab(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTabNodeId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.SessionSpecifics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.SessionSpecifics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.SessionSpecifics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionSpecifics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sync_pb.SessionHeader.serializeBinaryToWriter
    );
  }
  f = message.getTab();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sync_pb.SessionTab.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string session_tag = 1;
 * @return {string}
 */
proto.sync_pb.SessionSpecifics.prototype.getSessionTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sync_pb.SessionSpecifics.prototype.setSessionTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionSpecifics.prototype.clearSessionTag = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionSpecifics.prototype.hasSessionTag = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SessionHeader header = 2;
 * @return {?proto.sync_pb.SessionHeader}
 */
proto.sync_pb.SessionSpecifics.prototype.getHeader = function() {
  return /** @type{?proto.sync_pb.SessionHeader} */ (
    jspb.Message.getWrapperField(this, proto.sync_pb.SessionHeader, 2));
};


/** @param {?proto.sync_pb.SessionHeader|undefined} value */
proto.sync_pb.SessionSpecifics.prototype.setHeader = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.SessionSpecifics.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionSpecifics.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SessionTab tab = 3;
 * @return {?proto.sync_pb.SessionTab}
 */
proto.sync_pb.SessionSpecifics.prototype.getTab = function() {
  return /** @type{?proto.sync_pb.SessionTab} */ (
    jspb.Message.getWrapperField(this, proto.sync_pb.SessionTab, 3));
};


/** @param {?proto.sync_pb.SessionTab|undefined} value */
proto.sync_pb.SessionSpecifics.prototype.setTab = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.SessionSpecifics.prototype.clearTab = function() {
  this.setTab(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionSpecifics.prototype.hasTab = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 tab_node_id = 4;
 * @return {number}
 */
proto.sync_pb.SessionSpecifics.prototype.getTabNodeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, -1));
};


/** @param {number} value */
proto.sync_pb.SessionSpecifics.prototype.setTabNodeId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionSpecifics.prototype.clearTabNodeId = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionSpecifics.prototype.hasTabNodeId = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sync_pb.SessionHeader.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.SessionHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.SessionHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.SessionHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionHeader.toObject = function(includeInstance, msg) {
  var obj = {
    windowList: jspb.Message.toObjectList(msg.getWindowList(),
    proto.sync_pb.SessionWindow.toObject, includeInstance),
    clientName: jspb.Message.getField(msg, 3),
    deviceType: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.SessionHeader}
 */
proto.sync_pb.SessionHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.SessionHeader;
  return proto.sync_pb.SessionHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.SessionHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.SessionHeader}
 */
proto.sync_pb.SessionHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.sync_pb.SessionWindow;
      reader.readMessage(value,proto.sync_pb.SessionWindow.deserializeBinaryFromReader);
      msg.addWindow(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientName(value);
      break;
    case 4:
      var value = /** @type {!proto.sync_pb.SyncEnums.DeviceType} */ (reader.readEnum());
      msg.setDeviceType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.SessionHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.SessionHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.SessionHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWindowList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sync_pb.SessionWindow.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SyncEnums.DeviceType} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * repeated SessionWindow window = 2;
 * @return {!Array<!proto.sync_pb.SessionWindow>}
 */
proto.sync_pb.SessionHeader.prototype.getWindowList = function() {
  return /** @type{!Array<!proto.sync_pb.SessionWindow>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sync_pb.SessionWindow, 2));
};


/** @param {!Array<!proto.sync_pb.SessionWindow>} value */
proto.sync_pb.SessionHeader.prototype.setWindowList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sync_pb.SessionWindow=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sync_pb.SessionWindow}
 */
proto.sync_pb.SessionHeader.prototype.addWindow = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sync_pb.SessionWindow, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.SessionHeader.prototype.clearWindowList = function() {
  this.setWindowList([]);
};


/**
 * optional string client_name = 3;
 * @return {string}
 */
proto.sync_pb.SessionHeader.prototype.getClientName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.sync_pb.SessionHeader.prototype.setClientName = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionHeader.prototype.clearClientName = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionHeader.prototype.hasClientName = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SyncEnums.DeviceType device_type = 4;
 * @return {!proto.sync_pb.SyncEnums.DeviceType}
 */
proto.sync_pb.SessionHeader.prototype.getDeviceType = function() {
  return /** @type {!proto.sync_pb.SyncEnums.DeviceType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.sync_pb.SyncEnums.DeviceType} value */
proto.sync_pb.SessionHeader.prototype.setDeviceType = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionHeader.prototype.clearDeviceType = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionHeader.prototype.hasDeviceType = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sync_pb.SessionWindow.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.SessionWindow.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.SessionWindow.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.SessionWindow} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionWindow.toObject = function(includeInstance, msg) {
  var obj = {
    windowId: jspb.Message.getField(msg, 1),
    selectedTabIndex: jspb.Message.getFieldWithDefault(msg, 2, -1),
    browserType: jspb.Message.getFieldWithDefault(msg, 3, 1),
    tabList: jspb.Message.getRepeatedField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.SessionWindow}
 */
proto.sync_pb.SessionWindow.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.SessionWindow;
  return proto.sync_pb.SessionWindow.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.SessionWindow} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.SessionWindow}
 */
proto.sync_pb.SessionWindow.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWindowId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSelectedTabIndex(value);
      break;
    case 3:
      var value = /** @type {!proto.sync_pb.SessionWindow.BrowserType} */ (reader.readEnum());
      msg.setBrowserType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.addTab(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.SessionWindow.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.SessionWindow.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.SessionWindow} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionWindow.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SessionWindow.BrowserType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getTabList();
  if (f.length > 0) {
    writer.writeRepeatedInt32(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sync_pb.SessionWindow.BrowserType = {
  TYPE_TABBED: 1,
  TYPE_POPUP: 2,
  TYPE_CUSTOM_TAB: 3
};

/**
 * optional int32 window_id = 1;
 * @return {number}
 */
proto.sync_pb.SessionWindow.prototype.getWindowId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.sync_pb.SessionWindow.prototype.setWindowId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionWindow.prototype.clearWindowId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionWindow.prototype.hasWindowId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 selected_tab_index = 2;
 * @return {number}
 */
proto.sync_pb.SessionWindow.prototype.getSelectedTabIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, -1));
};


/** @param {number} value */
proto.sync_pb.SessionWindow.prototype.setSelectedTabIndex = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionWindow.prototype.clearSelectedTabIndex = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionWindow.prototype.hasSelectedTabIndex = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BrowserType browser_type = 3;
 * @return {!proto.sync_pb.SessionWindow.BrowserType}
 */
proto.sync_pb.SessionWindow.prototype.getBrowserType = function() {
  return /** @type {!proto.sync_pb.SessionWindow.BrowserType} */ (jspb.Message.getFieldWithDefault(this, 3, 1));
};


/** @param {!proto.sync_pb.SessionWindow.BrowserType} value */
proto.sync_pb.SessionWindow.prototype.setBrowserType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionWindow.prototype.clearBrowserType = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionWindow.prototype.hasBrowserType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated int32 tab = 4;
 * @return {!Array<number>}
 */
proto.sync_pb.SessionWindow.prototype.getTabList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.sync_pb.SessionWindow.prototype.setTabList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.sync_pb.SessionWindow.prototype.addTab = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.SessionWindow.prototype.clearTabList = function() {
  this.setTabList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sync_pb.SessionTab.repeatedFields_ = [7,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.SessionTab.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.SessionTab.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.SessionTab} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionTab.toObject = function(includeInstance, msg) {
  var obj = {
    tabId: jspb.Message.getFieldWithDefault(msg, 1, -1),
    windowId: jspb.Message.getField(msg, 2),
    tabVisualIndex: jspb.Message.getFieldWithDefault(msg, 3, -1),
    currentNavigationIndex: jspb.Message.getFieldWithDefault(msg, 4, -1),
    pinned: jspb.Message.getFieldWithDefault(msg, 5, false),
    extensionAppId: jspb.Message.getField(msg, 6),
    navigationList: jspb.Message.toObjectList(msg.getNavigationList(),
    proto.sync_pb.TabNavigation.toObject, includeInstance),
    favicon: msg.getFavicon_asB64(),
    faviconType: jspb.Message.getField(msg, 9),
    faviconSource: jspb.Message.getField(msg, 11),
    variationIdList: jspb.Message.getRepeatedField(msg, 12)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.SessionTab}
 */
proto.sync_pb.SessionTab.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.SessionTab;
  return proto.sync_pb.SessionTab.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.SessionTab} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.SessionTab}
 */
proto.sync_pb.SessionTab.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTabId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWindowId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTabVisualIndex(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCurrentNavigationIndex(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPinned(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtensionAppId(value);
      break;
    case 7:
      var value = new proto.sync_pb.TabNavigation;
      reader.readMessage(value,proto.sync_pb.TabNavigation.deserializeBinaryFromReader);
      msg.addNavigation(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFavicon(value);
      break;
    case 9:
      var value = /** @type {!proto.sync_pb.SessionTab.FaviconType} */ (reader.readEnum());
      msg.setFaviconType(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaviconSource(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.addVariationId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.SessionTab.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.SessionTab.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.SessionTab} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SessionTab.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getNavigationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.sync_pb.TabNavigation.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBytes(
      8,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SessionTab.FaviconType} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getVariationIdList();
  if (f.length > 0) {
    writer.writeRepeatedUint64(
      12,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sync_pb.SessionTab.FaviconType = {
  TYPE_WEB_FAVICON: 1
};

/**
 * optional int32 tab_id = 1;
 * @return {number}
 */
proto.sync_pb.SessionTab.prototype.getTabId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, -1));
};


/** @param {number} value */
proto.sync_pb.SessionTab.prototype.setTabId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearTabId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasTabId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 window_id = 2;
 * @return {number}
 */
proto.sync_pb.SessionTab.prototype.getWindowId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.sync_pb.SessionTab.prototype.setWindowId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearWindowId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasWindowId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 tab_visual_index = 3;
 * @return {number}
 */
proto.sync_pb.SessionTab.prototype.getTabVisualIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, -1));
};


/** @param {number} value */
proto.sync_pb.SessionTab.prototype.setTabVisualIndex = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearTabVisualIndex = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasTabVisualIndex = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 current_navigation_index = 4;
 * @return {number}
 */
proto.sync_pb.SessionTab.prototype.getCurrentNavigationIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, -1));
};


/** @param {number} value */
proto.sync_pb.SessionTab.prototype.setCurrentNavigationIndex = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearCurrentNavigationIndex = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasCurrentNavigationIndex = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool pinned = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.getPinned = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.sync_pb.SessionTab.prototype.setPinned = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearPinned = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasPinned = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string extension_app_id = 6;
 * @return {string}
 */
proto.sync_pb.SessionTab.prototype.getExtensionAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.sync_pb.SessionTab.prototype.setExtensionAppId = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearExtensionAppId = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasExtensionAppId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated TabNavigation navigation = 7;
 * @return {!Array<!proto.sync_pb.TabNavigation>}
 */
proto.sync_pb.SessionTab.prototype.getNavigationList = function() {
  return /** @type{!Array<!proto.sync_pb.TabNavigation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sync_pb.TabNavigation, 7));
};


/** @param {!Array<!proto.sync_pb.TabNavigation>} value */
proto.sync_pb.SessionTab.prototype.setNavigationList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.sync_pb.TabNavigation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sync_pb.TabNavigation}
 */
proto.sync_pb.SessionTab.prototype.addNavigation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.sync_pb.TabNavigation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.SessionTab.prototype.clearNavigationList = function() {
  this.setNavigationList([]);
};


/**
 * optional bytes favicon = 8;
 * @return {!(string|Uint8Array)}
 */
proto.sync_pb.SessionTab.prototype.getFavicon = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes favicon = 8;
 * This is a type-conversion wrapper around `getFavicon()`
 * @return {string}
 */
proto.sync_pb.SessionTab.prototype.getFavicon_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFavicon()));
};


/**
 * optional bytes favicon = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFavicon()`
 * @return {!Uint8Array}
 */
proto.sync_pb.SessionTab.prototype.getFavicon_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFavicon()));
};


/** @param {!(string|Uint8Array)} value */
proto.sync_pb.SessionTab.prototype.setFavicon = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearFavicon = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasFavicon = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional FaviconType favicon_type = 9;
 * @return {!proto.sync_pb.SessionTab.FaviconType}
 */
proto.sync_pb.SessionTab.prototype.getFaviconType = function() {
  return /** @type {!proto.sync_pb.SessionTab.FaviconType} */ (jspb.Message.getFieldWithDefault(this, 9, 1));
};


/** @param {!proto.sync_pb.SessionTab.FaviconType} value */
proto.sync_pb.SessionTab.prototype.setFaviconType = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearFaviconType = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasFaviconType = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string favicon_source = 11;
 * @return {string}
 */
proto.sync_pb.SessionTab.prototype.getFaviconSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.sync_pb.SessionTab.prototype.setFaviconSource = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SessionTab.prototype.clearFaviconSource = function() {
  jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SessionTab.prototype.hasFaviconSource = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated uint64 variation_id = 12;
 * @return {!Array<number>}
 */
proto.sync_pb.SessionTab.prototype.getVariationIdList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 12));
};


/** @param {!Array<number>} value */
proto.sync_pb.SessionTab.prototype.setVariationIdList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.sync_pb.SessionTab.prototype.addVariationId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.SessionTab.prototype.clearVariationIdList = function() {
  this.setVariationIdList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sync_pb.TabNavigation.repeatedFields_ = [19,23,28];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.TabNavigation.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.TabNavigation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.TabNavigation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.TabNavigation.toObject = function(includeInstance, msg) {
  var obj = {
    virtualUrl: jspb.Message.getField(msg, 2),
    referrer: jspb.Message.getField(msg, 3),
    title: jspb.Message.getField(msg, 4),
    pageTransition: jspb.Message.getFieldWithDefault(msg, 6, 0),
    redirectType: jspb.Message.getField(msg, 7),
    uniqueId: jspb.Message.getField(msg, 8),
    timestampMsec: jspb.Message.getField(msg, 9),
    navigationForwardBack: jspb.Message.getField(msg, 10),
    navigationFromAddressBar: jspb.Message.getField(msg, 11),
    navigationHomePage: jspb.Message.getField(msg, 12),
    navigationChainStart: jspb.Message.getField(msg, 13),
    navigationChainEnd: jspb.Message.getField(msg, 14),
    globalId: jspb.Message.getField(msg, 15),
    searchTerms: jspb.Message.getField(msg, 16),
    faviconUrl: jspb.Message.getField(msg, 17),
    blockedState: jspb.Message.getFieldWithDefault(msg, 18, 1),
    contentPackCategoriesList: jspb.Message.getRepeatedField(msg, 19),
    httpStatusCode: jspb.Message.getField(msg, 20),
    obsoleteReferrerPolicy: jspb.Message.getField(msg, 21),
    isRestored: jspb.Message.getField(msg, 22),
    navigationRedirectList: jspb.Message.toObjectList(msg.getNavigationRedirectList(),
    proto.sync_pb.NavigationRedirect.toObject, includeInstance),
    lastNavigationRedirectUrl: jspb.Message.getField(msg, 24),
    correctReferrerPolicy: jspb.Message.getFieldWithDefault(msg, 25, 1),
    passwordState: jspb.Message.getField(msg, 26),
    taskId: jspb.Message.getField(msg, 27),
    ancestorTaskIdList: jspb.Message.getRepeatedField(msg, 28),
    replacedNavigation: (f = msg.getReplacedNavigation()) && proto.sync_pb.ReplacedNavigation.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.TabNavigation}
 */
proto.sync_pb.TabNavigation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.TabNavigation;
  return proto.sync_pb.TabNavigation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.TabNavigation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.TabNavigation}
 */
proto.sync_pb.TabNavigation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVirtualUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferrer(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 6:
      var value = /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (reader.readEnum());
      msg.setPageTransition(value);
      break;
    case 7:
      var value = /** @type {!proto.sync_pb.SyncEnums.PageTransitionRedirectType} */ (reader.readEnum());
      msg.setRedirectType(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUniqueId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestampMsec(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNavigationForwardBack(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNavigationFromAddressBar(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNavigationHomePage(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNavigationChainStart(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNavigationChainEnd(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setGlobalId(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchTerms(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaviconUrl(value);
      break;
    case 18:
      var value = /** @type {!proto.sync_pb.TabNavigation.BlockedState} */ (reader.readEnum());
      msg.setBlockedState(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.addContentPackCategories(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHttpStatusCode(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setObsoleteReferrerPolicy(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRestored(value);
      break;
    case 23:
      var value = new proto.sync_pb.NavigationRedirect;
      reader.readMessage(value,proto.sync_pb.NavigationRedirect.deserializeBinaryFromReader);
      msg.addNavigationRedirect(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastNavigationRedirectUrl(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCorrectReferrerPolicy(value);
      break;
    case 26:
      var value = /** @type {!proto.sync_pb.TabNavigation.PasswordState} */ (reader.readEnum());
      msg.setPasswordState(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTaskId(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readInt64());
      msg.addAncestorTaskId(value);
      break;
    case 29:
      var value = new proto.sync_pb.ReplacedNavigation;
      reader.readMessage(value,proto.sync_pb.ReplacedNavigation.deserializeBinaryFromReader);
      msg.setReplacedNavigation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.TabNavigation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.TabNavigation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.TabNavigation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.TabNavigation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SyncEnums.PageTransitionRedirectType} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeBool(
      10,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBool(
      11,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeBool(
      12,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeBool(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeBool(
      14,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeInt64(
      15,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeString(
      16,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeString(
      17,
      f
    );
  }
  f = /** @type {!proto.sync_pb.TabNavigation.BlockedState} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeEnum(
      18,
      f
    );
  }
  f = message.getContentPackCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      19,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 20));
  if (f != null) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeInt32(
      21,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeBool(
      22,
      f
    );
  }
  f = message.getNavigationRedirectList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      23,
      f,
      proto.sync_pb.NavigationRedirect.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 24));
  if (f != null) {
    writer.writeString(
      24,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 25));
  if (f != null) {
    writer.writeInt32(
      25,
      f
    );
  }
  f = /** @type {!proto.sync_pb.TabNavigation.PasswordState} */ (jspb.Message.getField(message, 26));
  if (f != null) {
    writer.writeEnum(
      26,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 27));
  if (f != null) {
    writer.writeInt64(
      27,
      f
    );
  }
  f = message.getAncestorTaskIdList();
  if (f.length > 0) {
    writer.writeRepeatedInt64(
      28,
      f
    );
  }
  f = message.getReplacedNavigation();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      proto.sync_pb.ReplacedNavigation.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.sync_pb.TabNavigation.BlockedState = {
  STATE_ALLOWED: 1,
  STATE_BLOCKED: 2
};

/**
 * @enum {number}
 */
proto.sync_pb.TabNavigation.PasswordState = {
  PASSWORD_STATE_UNKNOWN: 0,
  NO_PASSWORD_FIELD: 1,
  HAS_PASSWORD_FIELD: 2
};

/**
 * optional string virtual_url = 2;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getVirtualUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setVirtualUrl = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearVirtualUrl = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasVirtualUrl = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string referrer = 3;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getReferrer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setReferrer = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearReferrer = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasReferrer = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearTitle = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasTitle = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional SyncEnums.PageTransition page_transition = 6;
 * @return {!proto.sync_pb.SyncEnums.PageTransition}
 */
proto.sync_pb.TabNavigation.prototype.getPageTransition = function() {
  return /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.sync_pb.SyncEnums.PageTransition} value */
proto.sync_pb.TabNavigation.prototype.setPageTransition = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearPageTransition = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasPageTransition = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SyncEnums.PageTransitionRedirectType redirect_type = 7;
 * @return {!proto.sync_pb.SyncEnums.PageTransitionRedirectType}
 */
proto.sync_pb.TabNavigation.prototype.getRedirectType = function() {
  return /** @type {!proto.sync_pb.SyncEnums.PageTransitionRedirectType} */ (jspb.Message.getFieldWithDefault(this, 7, 1));
};


/** @param {!proto.sync_pb.SyncEnums.PageTransitionRedirectType} value */
proto.sync_pb.TabNavigation.prototype.setRedirectType = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearRedirectType = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasRedirectType = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int32 unique_id = 8;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getUniqueId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setUniqueId = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearUniqueId = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasUniqueId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int64 timestamp_msec = 9;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getTimestampMsec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setTimestampMsec = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearTimestampMsec = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasTimestampMsec = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool navigation_forward_back = 10;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationForwardBack = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 10, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setNavigationForwardBack = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationForwardBack = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasNavigationForwardBack = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool navigation_from_address_bar = 11;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationFromAddressBar = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 11, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setNavigationFromAddressBar = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationFromAddressBar = function() {
  jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasNavigationFromAddressBar = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool navigation_home_page = 12;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationHomePage = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 12, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setNavigationHomePage = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationHomePage = function() {
  jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasNavigationHomePage = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool navigation_chain_start = 13;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationChainStart = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 13, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setNavigationChainStart = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationChainStart = function() {
  jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasNavigationChainStart = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool navigation_chain_end = 14;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationChainEnd = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 14, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setNavigationChainEnd = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationChainEnd = function() {
  jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasNavigationChainEnd = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional int64 global_id = 15;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getGlobalId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setGlobalId = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearGlobalId = function() {
  jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasGlobalId = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string search_terms = 16;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getSearchTerms = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setSearchTerms = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearSearchTerms = function() {
  jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasSearchTerms = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string favicon_url = 17;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getFaviconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setFaviconUrl = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearFaviconUrl = function() {
  jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasFaviconUrl = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional BlockedState blocked_state = 18;
 * @return {!proto.sync_pb.TabNavigation.BlockedState}
 */
proto.sync_pb.TabNavigation.prototype.getBlockedState = function() {
  return /** @type {!proto.sync_pb.TabNavigation.BlockedState} */ (jspb.Message.getFieldWithDefault(this, 18, 1));
};


/** @param {!proto.sync_pb.TabNavigation.BlockedState} value */
proto.sync_pb.TabNavigation.prototype.setBlockedState = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearBlockedState = function() {
  jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasBlockedState = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * repeated string content_pack_categories = 19;
 * @return {!Array<string>}
 */
proto.sync_pb.TabNavigation.prototype.getContentPackCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 19));
};


/** @param {!Array<string>} value */
proto.sync_pb.TabNavigation.prototype.setContentPackCategoriesList = function(value) {
  jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.sync_pb.TabNavigation.prototype.addContentPackCategories = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.TabNavigation.prototype.clearContentPackCategoriesList = function() {
  this.setContentPackCategoriesList([]);
};


/**
 * optional int32 http_status_code = 20;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getHttpStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setHttpStatusCode = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearHttpStatusCode = function() {
  jspb.Message.setField(this, 20, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasHttpStatusCode = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional int32 obsolete_referrer_policy = 21;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getObsoleteReferrerPolicy = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setObsoleteReferrerPolicy = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearObsoleteReferrerPolicy = function() {
  jspb.Message.setField(this, 21, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasObsoleteReferrerPolicy = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional bool is_restored = 22;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.getIsRestored = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 22, false));
};


/** @param {boolean} value */
proto.sync_pb.TabNavigation.prototype.setIsRestored = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearIsRestored = function() {
  jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasIsRestored = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * repeated NavigationRedirect navigation_redirect = 23;
 * @return {!Array<!proto.sync_pb.NavigationRedirect>}
 */
proto.sync_pb.TabNavigation.prototype.getNavigationRedirectList = function() {
  return /** @type{!Array<!proto.sync_pb.NavigationRedirect>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sync_pb.NavigationRedirect, 23));
};


/** @param {!Array<!proto.sync_pb.NavigationRedirect>} value */
proto.sync_pb.TabNavigation.prototype.setNavigationRedirectList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 23, value);
};


/**
 * @param {!proto.sync_pb.NavigationRedirect=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sync_pb.NavigationRedirect}
 */
proto.sync_pb.TabNavigation.prototype.addNavigationRedirect = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 23, opt_value, proto.sync_pb.NavigationRedirect, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.TabNavigation.prototype.clearNavigationRedirectList = function() {
  this.setNavigationRedirectList([]);
};


/**
 * optional string last_navigation_redirect_url = 24;
 * @return {string}
 */
proto.sync_pb.TabNavigation.prototype.getLastNavigationRedirectUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/** @param {string} value */
proto.sync_pb.TabNavigation.prototype.setLastNavigationRedirectUrl = function(value) {
  jspb.Message.setField(this, 24, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearLastNavigationRedirectUrl = function() {
  jspb.Message.setField(this, 24, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasLastNavigationRedirectUrl = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional int32 correct_referrer_policy = 25;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getCorrectReferrerPolicy = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 1));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setCorrectReferrerPolicy = function(value) {
  jspb.Message.setField(this, 25, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearCorrectReferrerPolicy = function() {
  jspb.Message.setField(this, 25, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasCorrectReferrerPolicy = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional PasswordState password_state = 26;
 * @return {!proto.sync_pb.TabNavigation.PasswordState}
 */
proto.sync_pb.TabNavigation.prototype.getPasswordState = function() {
  return /** @type {!proto.sync_pb.TabNavigation.PasswordState} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/** @param {!proto.sync_pb.TabNavigation.PasswordState} value */
proto.sync_pb.TabNavigation.prototype.setPasswordState = function(value) {
  jspb.Message.setField(this, 26, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearPasswordState = function() {
  jspb.Message.setField(this, 26, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasPasswordState = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional int64 task_id = 27;
 * @return {number}
 */
proto.sync_pb.TabNavigation.prototype.getTaskId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/** @param {number} value */
proto.sync_pb.TabNavigation.prototype.setTaskId = function(value) {
  jspb.Message.setField(this, 27, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearTaskId = function() {
  jspb.Message.setField(this, 27, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasTaskId = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * repeated int64 ancestor_task_id = 28;
 * @return {!Array<number>}
 */
proto.sync_pb.TabNavigation.prototype.getAncestorTaskIdList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 28));
};


/** @param {!Array<number>} value */
proto.sync_pb.TabNavigation.prototype.setAncestorTaskIdList = function(value) {
  jspb.Message.setField(this, 28, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.sync_pb.TabNavigation.prototype.addAncestorTaskId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 28, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.TabNavigation.prototype.clearAncestorTaskIdList = function() {
  this.setAncestorTaskIdList([]);
};


/**
 * optional ReplacedNavigation replaced_navigation = 29;
 * @return {?proto.sync_pb.ReplacedNavigation}
 */
proto.sync_pb.TabNavigation.prototype.getReplacedNavigation = function() {
  return /** @type{?proto.sync_pb.ReplacedNavigation} */ (
    jspb.Message.getWrapperField(this, proto.sync_pb.ReplacedNavigation, 29));
};


/** @param {?proto.sync_pb.ReplacedNavigation|undefined} value */
proto.sync_pb.TabNavigation.prototype.setReplacedNavigation = function(value) {
  jspb.Message.setWrapperField(this, 29, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.TabNavigation.prototype.clearReplacedNavigation = function() {
  this.setReplacedNavigation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.TabNavigation.prototype.hasReplacedNavigation = function() {
  return jspb.Message.getField(this, 29) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.NavigationRedirect.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.NavigationRedirect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.NavigationRedirect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.NavigationRedirect.toObject = function(includeInstance, msg) {
  var obj = {
    url: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.NavigationRedirect}
 */
proto.sync_pb.NavigationRedirect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.NavigationRedirect;
  return proto.sync_pb.NavigationRedirect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.NavigationRedirect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.NavigationRedirect}
 */
proto.sync_pb.NavigationRedirect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.NavigationRedirect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.NavigationRedirect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.NavigationRedirect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.NavigationRedirect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.sync_pb.NavigationRedirect.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sync_pb.NavigationRedirect.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.NavigationRedirect.prototype.clearUrl = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.NavigationRedirect.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.ReplacedNavigation.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.ReplacedNavigation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.ReplacedNavigation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.ReplacedNavigation.toObject = function(includeInstance, msg) {
  var obj = {
    firstCommittedUrl: jspb.Message.getField(msg, 1),
    firstTimestampMsec: jspb.Message.getField(msg, 2),
    firstPageTransition: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.ReplacedNavigation}
 */
proto.sync_pb.ReplacedNavigation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.ReplacedNavigation;
  return proto.sync_pb.ReplacedNavigation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.ReplacedNavigation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.ReplacedNavigation}
 */
proto.sync_pb.ReplacedNavigation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstCommittedUrl(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFirstTimestampMsec(value);
      break;
    case 3:
      var value = /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (reader.readEnum());
      msg.setFirstPageTransition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.ReplacedNavigation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.ReplacedNavigation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.ReplacedNavigation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.ReplacedNavigation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string first_committed_url = 1;
 * @return {string}
 */
proto.sync_pb.ReplacedNavigation.prototype.getFirstCommittedUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sync_pb.ReplacedNavigation.prototype.setFirstCommittedUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ReplacedNavigation.prototype.clearFirstCommittedUrl = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ReplacedNavigation.prototype.hasFirstCommittedUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 first_timestamp_msec = 2;
 * @return {number}
 */
proto.sync_pb.ReplacedNavigation.prototype.getFirstTimestampMsec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.sync_pb.ReplacedNavigation.prototype.setFirstTimestampMsec = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ReplacedNavigation.prototype.clearFirstTimestampMsec = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ReplacedNavigation.prototype.hasFirstTimestampMsec = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SyncEnums.PageTransition first_page_transition = 3;
 * @return {!proto.sync_pb.SyncEnums.PageTransition}
 */
proto.sync_pb.ReplacedNavigation.prototype.getFirstPageTransition = function() {
  return /** @type {!proto.sync_pb.SyncEnums.PageTransition} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.sync_pb.SyncEnums.PageTransition} value */
proto.sync_pb.ReplacedNavigation.prototype.setFirstPageTransition = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.ReplacedNavigation.prototype.clearFirstPageTransition = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.ReplacedNavigation.prototype.hasFirstPageTransition = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.sync_pb);
