/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var extension_setting_specifics_pb = require('./extension_setting_specifics_pb.js');
goog.object.extend(proto, extension_setting_specifics_pb);
goog.exportSymbol('proto.sync_pb.AppSettingSpecifics', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.AppSettingSpecifics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.AppSettingSpecifics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.AppSettingSpecifics.displayName = 'proto.sync_pb.AppSettingSpecifics';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.AppSettingSpecifics.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.AppSettingSpecifics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.AppSettingSpecifics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.AppSettingSpecifics.toObject = function(includeInstance, msg) {
  var obj = {
    extensionSetting: (f = msg.getExtensionSetting()) && extension_setting_specifics_pb.ExtensionSettingSpecifics.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.AppSettingSpecifics}
 */
proto.sync_pb.AppSettingSpecifics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.AppSettingSpecifics;
  return proto.sync_pb.AppSettingSpecifics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.AppSettingSpecifics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.AppSettingSpecifics}
 */
proto.sync_pb.AppSettingSpecifics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new extension_setting_specifics_pb.ExtensionSettingSpecifics;
      reader.readMessage(value,extension_setting_specifics_pb.ExtensionSettingSpecifics.deserializeBinaryFromReader);
      msg.setExtensionSetting(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.AppSettingSpecifics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.AppSettingSpecifics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.AppSettingSpecifics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.AppSettingSpecifics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExtensionSetting();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      extension_setting_specifics_pb.ExtensionSettingSpecifics.serializeBinaryToWriter
    );
  }
};


/**
 * optional ExtensionSettingSpecifics extension_setting = 1;
 * @return {?proto.sync_pb.ExtensionSettingSpecifics}
 */
proto.sync_pb.AppSettingSpecifics.prototype.getExtensionSetting = function() {
  return /** @type{?proto.sync_pb.ExtensionSettingSpecifics} */ (
    jspb.Message.getWrapperField(this, extension_setting_specifics_pb.ExtensionSettingSpecifics, 1));
};


/** @param {?proto.sync_pb.ExtensionSettingSpecifics|undefined} value */
proto.sync_pb.AppSettingSpecifics.prototype.setExtensionSetting = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.sync_pb.AppSettingSpecifics.prototype.clearExtensionSetting = function() {
  this.setExtensionSetting(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.AppSettingSpecifics.prototype.hasExtensionSetting = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.sync_pb);
