/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sync_pb.SearchEngineSpecifics', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.SearchEngineSpecifics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sync_pb.SearchEngineSpecifics.repeatedFields_, null);
};
goog.inherits(proto.sync_pb.SearchEngineSpecifics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.SearchEngineSpecifics.displayName = 'proto.sync_pb.SearchEngineSpecifics';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sync_pb.SearchEngineSpecifics.repeatedFields_ = [19];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.SearchEngineSpecifics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.SearchEngineSpecifics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SearchEngineSpecifics.toObject = function(includeInstance, msg) {
  var obj = {
    shortName: jspb.Message.getField(msg, 1),
    keyword: jspb.Message.getField(msg, 2),
    faviconUrl: jspb.Message.getField(msg, 3),
    url: jspb.Message.getField(msg, 4),
    safeForAutoreplace: jspb.Message.getField(msg, 5),
    originatingUrl: jspb.Message.getField(msg, 6),
    dateCreated: jspb.Message.getField(msg, 7),
    inputEncodings: jspb.Message.getField(msg, 8),
    deprecatedShowInDefaultList: jspb.Message.getField(msg, 9),
    suggestionsUrl: jspb.Message.getField(msg, 10),
    prepopulateId: jspb.Message.getField(msg, 11),
    autogenerateKeyword: jspb.Message.getField(msg, 12),
    instantUrl: jspb.Message.getField(msg, 15),
    lastModified: jspb.Message.getField(msg, 17),
    syncGuid: jspb.Message.getField(msg, 18),
    alternateUrlsList: jspb.Message.getRepeatedField(msg, 19),
    searchTermsReplacementKey: jspb.Message.getField(msg, 20),
    imageUrl: jspb.Message.getField(msg, 21),
    searchUrlPostParams: jspb.Message.getField(msg, 22),
    suggestionsUrlPostParams: jspb.Message.getField(msg, 23),
    instantUrlPostParams: jspb.Message.getField(msg, 24),
    imageUrlPostParams: jspb.Message.getField(msg, 25),
    newTabUrl: jspb.Message.getField(msg, 26)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.SearchEngineSpecifics}
 */
proto.sync_pb.SearchEngineSpecifics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.SearchEngineSpecifics;
  return proto.sync_pb.SearchEngineSpecifics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.SearchEngineSpecifics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.SearchEngineSpecifics}
 */
proto.sync_pb.SearchEngineSpecifics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyword(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaviconUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSafeForAutoreplace(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginatingUrl(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateCreated(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setInputEncodings(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeprecatedShowInDefaultList(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSuggestionsUrl(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrepopulateId(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutogenerateKeyword(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstantUrl(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastModified(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setSyncGuid(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.addAlternateUrls(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchTermsReplacementKey(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageUrl(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchUrlPostParams(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setSuggestionsUrlPostParams(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstantUrlPostParams(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageUrlPostParams(value);
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewTabUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.SearchEngineSpecifics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.SearchEngineSpecifics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.SearchEngineSpecifics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeBool(
      12,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeInt64(
      17,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getAlternateUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      19,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 20));
  if (f != null) {
    writer.writeString(
      20,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeString(
      21,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeString(
      22,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 23));
  if (f != null) {
    writer.writeString(
      23,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 24));
  if (f != null) {
    writer.writeString(
      24,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 25));
  if (f != null) {
    writer.writeString(
      25,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 26));
  if (f != null) {
    writer.writeString(
      26,
      f
    );
  }
};


/**
 * optional string short_name = 1;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getShortName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setShortName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearShortName = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasShortName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string keyword = 2;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getKeyword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setKeyword = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearKeyword = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasKeyword = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string favicon_url = 3;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getFaviconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setFaviconUrl = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearFaviconUrl = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasFaviconUrl = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string url = 4;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearUrl = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool safe_for_autoreplace = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSafeForAutoreplace = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSafeForAutoreplace = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSafeForAutoreplace = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSafeForAutoreplace = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string originating_url = 6;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getOriginatingUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setOriginatingUrl = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearOriginatingUrl = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasOriginatingUrl = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 date_created = 7;
 * @return {number}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getDateCreated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setDateCreated = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearDateCreated = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasDateCreated = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string input_encodings = 8;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getInputEncodings = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setInputEncodings = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearInputEncodings = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasInputEncodings = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool deprecated_show_in_default_list = 9;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getDeprecatedShowInDefaultList = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 9, false));
};


/** @param {boolean} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setDeprecatedShowInDefaultList = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearDeprecatedShowInDefaultList = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasDeprecatedShowInDefaultList = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string suggestions_url = 10;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSuggestionsUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSuggestionsUrl = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSuggestionsUrl = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSuggestionsUrl = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 prepopulate_id = 11;
 * @return {number}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getPrepopulateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setPrepopulateId = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearPrepopulateId = function() {
  jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasPrepopulateId = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool autogenerate_keyword = 12;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getAutogenerateKeyword = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 12, false));
};


/** @param {boolean} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setAutogenerateKeyword = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearAutogenerateKeyword = function() {
  jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasAutogenerateKeyword = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string instant_url = 15;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getInstantUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setInstantUrl = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearInstantUrl = function() {
  jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasInstantUrl = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional int64 last_modified = 17;
 * @return {number}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getLastModified = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setLastModified = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearLastModified = function() {
  jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasLastModified = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional string sync_guid = 18;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSyncGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSyncGuid = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSyncGuid = function() {
  jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSyncGuid = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * repeated string alternate_urls = 19;
 * @return {!Array<string>}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getAlternateUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 19));
};


/** @param {!Array<string>} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setAlternateUrlsList = function(value) {
  jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.sync_pb.SearchEngineSpecifics.prototype.addAlternateUrls = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearAlternateUrlsList = function() {
  this.setAlternateUrlsList([]);
};


/**
 * optional string search_terms_replacement_key = 20;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSearchTermsReplacementKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSearchTermsReplacementKey = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSearchTermsReplacementKey = function() {
  jspb.Message.setField(this, 20, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSearchTermsReplacementKey = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional string image_url = 21;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getImageUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setImageUrl = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearImageUrl = function() {
  jspb.Message.setField(this, 21, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasImageUrl = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional string search_url_post_params = 22;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSearchUrlPostParams = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSearchUrlPostParams = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSearchUrlPostParams = function() {
  jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSearchUrlPostParams = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional string suggestions_url_post_params = 23;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getSuggestionsUrlPostParams = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setSuggestionsUrlPostParams = function(value) {
  jspb.Message.setField(this, 23, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearSuggestionsUrlPostParams = function() {
  jspb.Message.setField(this, 23, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasSuggestionsUrlPostParams = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional string instant_url_post_params = 24;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getInstantUrlPostParams = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setInstantUrlPostParams = function(value) {
  jspb.Message.setField(this, 24, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearInstantUrlPostParams = function() {
  jspb.Message.setField(this, 24, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasInstantUrlPostParams = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional string image_url_post_params = 25;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getImageUrlPostParams = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setImageUrlPostParams = function(value) {
  jspb.Message.setField(this, 25, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearImageUrlPostParams = function() {
  jspb.Message.setField(this, 25, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasImageUrlPostParams = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional string new_tab_url = 26;
 * @return {string}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.getNewTabUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 26, ""));
};


/** @param {string} value */
proto.sync_pb.SearchEngineSpecifics.prototype.setNewTabUrl = function(value) {
  jspb.Message.setField(this, 26, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.SearchEngineSpecifics.prototype.clearNewTabUrl = function() {
  jspb.Message.setField(this, 26, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.SearchEngineSpecifics.prototype.hasNewTabUrl = function() {
  return jspb.Message.getField(this, 26) != null;
};


goog.object.extend(exports, proto.sync_pb);
