/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sync_pb.WifiCredentialSpecifics', null, global);
goog.exportSymbol('proto.sync_pb.WifiCredentialSpecifics.SecurityClass', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sync_pb.WifiCredentialSpecifics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sync_pb.WifiCredentialSpecifics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sync_pb.WifiCredentialSpecifics.displayName = 'proto.sync_pb.WifiCredentialSpecifics';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.toObject = function(opt_includeInstance) {
  return proto.sync_pb.WifiCredentialSpecifics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sync_pb.WifiCredentialSpecifics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.WifiCredentialSpecifics.toObject = function(includeInstance, msg) {
  var obj = {
    ssid: msg.getSsid_asB64(),
    securityClass: jspb.Message.getField(msg, 2),
    passphrase: msg.getPassphrase_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sync_pb.WifiCredentialSpecifics}
 */
proto.sync_pb.WifiCredentialSpecifics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sync_pb.WifiCredentialSpecifics;
  return proto.sync_pb.WifiCredentialSpecifics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sync_pb.WifiCredentialSpecifics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sync_pb.WifiCredentialSpecifics}
 */
proto.sync_pb.WifiCredentialSpecifics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSsid(value);
      break;
    case 2:
      var value = /** @type {!proto.sync_pb.WifiCredentialSpecifics.SecurityClass} */ (reader.readEnum());
      msg.setSecurityClass(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPassphrase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sync_pb.WifiCredentialSpecifics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sync_pb.WifiCredentialSpecifics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sync_pb.WifiCredentialSpecifics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = /** @type {!proto.sync_pb.WifiCredentialSpecifics.SecurityClass} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sync_pb.WifiCredentialSpecifics.SecurityClass = {
  SECURITY_CLASS_INVALID: 0,
  SECURITY_CLASS_NONE: 1,
  SECURITY_CLASS_WEP: 2,
  SECURITY_CLASS_PSK: 3
};

/**
 * optional bytes ssid = 1;
 * @return {!(string|Uint8Array)}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getSsid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes ssid = 1;
 * This is a type-conversion wrapper around `getSsid()`
 * @return {string}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getSsid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSsid()));
};


/**
 * optional bytes ssid = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSsid()`
 * @return {!Uint8Array}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getSsid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSsid()));
};


/** @param {!(string|Uint8Array)} value */
proto.sync_pb.WifiCredentialSpecifics.prototype.setSsid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.clearSsid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.hasSsid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SecurityClass security_class = 2;
 * @return {!proto.sync_pb.WifiCredentialSpecifics.SecurityClass}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getSecurityClass = function() {
  return /** @type {!proto.sync_pb.WifiCredentialSpecifics.SecurityClass} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.sync_pb.WifiCredentialSpecifics.SecurityClass} value */
proto.sync_pb.WifiCredentialSpecifics.prototype.setSecurityClass = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.clearSecurityClass = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.hasSecurityClass = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes passphrase = 3;
 * @return {!(string|Uint8Array)}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getPassphrase = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes passphrase = 3;
 * This is a type-conversion wrapper around `getPassphrase()`
 * @return {string}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getPassphrase_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPassphrase()));
};


/**
 * optional bytes passphrase = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPassphrase()`
 * @return {!Uint8Array}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.getPassphrase_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPassphrase()));
};


/** @param {!(string|Uint8Array)} value */
proto.sync_pb.WifiCredentialSpecifics.prototype.setPassphrase = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.clearPassphrase = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sync_pb.WifiCredentialSpecifics.prototype.hasPassphrase = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.sync_pb);
